[package]
name = "envtricks"
description = ".env file manipulation utilities"
version = "0.1.0"
license = "MIT"
edition = "2024"
repository = "https://github.com/intervinn/envtricks"
readme = "README.md"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }

